import '@fortawesome/fontawesome-free/js/all';
import 'swiper/css';
import './main.scss';
import './components/typography/typography.scss';
import './components/container.scss';
import './components/form/form.js';
import './components/header/header.js';
import './components/navigation/navigation.js';
import './components/header-banner/header-banner.js';
import './components/button/button.js';
import './components/top-brands/top-brands.js';
console.log('Hello IT-academy student 🚀');
